---

# Задача 1.20. Эквивалентность квадратичных форм

## Условие

Эквивалентны ли над полем вещественных чисел квадратичные формы $Q_1$ и $Q_2$, где
$$Q_1 = 2x_1^2 + 9x_2^2 + 3x_3^2 + 8x_1x_2 - 4x_1x_3 - 10x_2x_3;$$
$$Q_2 = 2x_1^2 + 3x_2^2 + 6x_3^2 - 4x_1x_2 - 4x_1x_3 + 8x_2x_3.$$

> Почему квадрат второй? Потому что квадратичная форма для трёх неизвестных. Очепятка в задании (надеюсь и верю)

## Теоретическая часть

### 1. Эквивалентность квадратичных форм

Определение. Две квадратичные формы $Q_1$ и $Q_2$ называются эквивалентными над полем $\mathbb{F}$, если существует невырожденное линейное преобразование $x = Cy$ ($\det C \neq 0$), переводящее одну форму в другую: $Q_1(x) = Q_2(Cy)$.

В матричной форме: $A_1 = C^T A_2 C$, где $A_1, A_2$ — матрицы форм, $C$ — невырожденная матрица.

<details>
<summary><b>Поясняю на котиках (Вырезать перед прикреплением на сдачу)</b></summary>

Представь, что у нас есть **Котик**, и мы хотим измерить его **Счастье** (это и есть наша квадратичная форма $Q$). 

Счастье котика зависит от двух факторов: количества вкусняшек и количества почёсываний за ушком. Но вот проблема: разные люди измеряют это по-разному.

**Алиса** смотрит на котика. Она измеряет вкусняшки в **граммах** ($x_1$), а почёсывания в **секундах** ($x_2$). 
Она вывела свою формулу счастья: $Q_1(x)$. И записала её в виде матрицы $A_1$.

**Боб** тоже смотрит на того же самого котика. Но он ленивый и не хочет возиться с граммами и секундами. Он измеряет вкусняшки в **порциях** ($y_1$), а почёсывания в **минутах** ($y_2$).
Боб выводит свою формулу счастья: $Q_2(y)$. И записывает её в виде матрицы $A_2$.

Котик один и тот же. Его счастье одно и то же. Значит, если Алиса и Боб наблюдают одно и то же состояние котика, их формулы должны выдавать **одно и то же число счастья**:
$$Q_1(x) = Q_2(y)$$

Но как связаны их единицы измерения? Боб может перевести свои "порции" и "минуты" в алисины "граммы" и "секунды":
- 1 порция = 50 грамм $\Rightarrow x_1 = 50 y_1$
- 1 минута = 60 секунд $\Rightarrow x_2 = 60 y_2$

Это линейное преобразование! В матричном виде оно записывается как **$x = Cy$**, где матрица $C$ — это просто коэффициенты перевода единиц:
$$C = \begin{pmatrix} 50 & 0 \\ 0 & 60 \end{pmatrix}$$

*Важный момент:* $\det C = 3000 \neq 0$. Это значит, что Боб не потерял ни одну из переменных (он не начал измерять и то, и другое только в "попугаях"). Преобразование **невырожденное**, то есть обратимое. Мы всегда можем перевести граммы обратно в порции.

Теперь самое интересное. Алиса и Боб записали свои формулы в виде матриц $A_1$ и $A_2$. 
Поскольку они описывают *одного и того же котика*, их матрицы не могут быть совершенно разными. Они связаны через матрицу перевода $C$:
$$A_1 = C^T A_2 C$$

**Главный вывод:** Если две формы эквивалентны, это значит, что **они описывают одну и ту же суть, просто на разных языках**. 

А раз суть одна, у них есть **инварианты** — свойства, которые НЕ меняются при смене координат (при смене Алисы на Боба). 
Самый главный инвариант для квадратичных форм (Закон инерции Сильвестра): **количество положительных, отрицательных и нулевых собственных значений (знаков) у матриц $A_1$ и $A_2$ всегда одинаковое!**

**Перевод на кошачий:**
Если Алиса посчитала, что матрица её формы *положительно определённая* (все собственные значения $> 0$, то есть котик всегда счастлив, и его счастье растёт от еды и ласки), то и Боб, посчитав свою матрицу $A_2$ в своих "порциях и минутах", **обязан** получить, что его форма тоже *положительно определённая*. 

Котик не может быть одновременно вечно счастливым в граммах и вечно грустным в порциях. Математика это гарантирует! 🐈🐾

p.s. ДА КТО ТАКОЙ ЭТОТ ВАШ СТАС???

</details>

### 2. Закон инерции Сильвестра

**Теорема (Закон инерции Сильвестра).** При любом приведении квадратичной формы к каноническому (диагональному) виду число положительных и число отрицательных коэффициентов остаётся неизменным. Эта пара чисел $(n_+, n_-)$ называется **сигнатурой** формы.

**Следствие.** Две квадратичные формы над полем $\mathbb{R}$ эквивалентны тогда и только тогда, когда они имеют **одинаковую сигнатуру** (одинаковое число положительных и отрицательных квадратов в каноническом виде).

**Почему это работает?** Любая вещественная симметричная матрица диагонализуема ортогональным преобразованием (спектральная теорема). Собственные значения матрицы квадратичной формы определяют знаки коэффициентов в каноническом виде. Поскольку ортогональное преобразование невырождено, сигнатура является инвариантом формы относительно невырожденных замен переменных.

<details>
<summary><b>Разбор терминов — что это вообще значит (Вырезать перед прикреплением на сдачу)</b></summary>

#### 1. Что такое **канонический вид** квадратичной формы?

Представь, что у тебя есть квадратичная форма — это многочлен второй степени от нескольких переменных. Например:
$$Q(x, y) = 3x^2 + 4xy + 5y^2$$

Здесь есть **перекрёстный член** $4xy$ — он связывает переменные $x$ и $y$.

**Канонический вид** — это когда ты избавился от всех перекрёстных членов, и форма выглядит как простая сумма квадратов:
$$Q(y_1, y_2) = \lambda_1 y_1^2 + \lambda_2 y_2^2$$

Где $y_1, y_2$ — это какие-то новые переменные (полученные после замены координат), а $\lambda_1, \lambda_2$ — коэффициенты.

**Аналогия:** Это как если бы ты взял сложный SQL-запрос с кучей JOIN'ов и подзапросов, а потом переписал его в виде простого `SELECT * FROM table WHERE ...` — та же логика, но структура прозрачная.

---

#### 2. Что за **пара чисел $(n_+, n_-)$**?

Когда ты привёл форму к каноническому виду, у тебя есть коэффициенты $\lambda_i$ при каждом квадрате $y_i^2$.

- $n_+$ — это **количество положительных** коэффициентов (сколько раз $\lambda_i > 0$)
- $n_-$ — это **количество отрицательных** коэффициентов (сколько раз $\lambda_i < 0$)

**Пример:**
$$Q(y_1, y_2, y_3) = 2y_1^2 - 3y_2^2 + 5y_3^2$$

Здесь:
- $n_+ = 2$ (коэффициенты $2$ и $5$ положительные)
- $n_- = 1$ (коэффициент $-3$ отрицательный)

Эта пара $(n_+, n_-) = (2, 1)$ и называется **сигнатурой** формы.

---

#### 3. Как **квадраты могут быть отрицательными**?

Важно понимать: сам квадрат $y^2$ всегда неотрицательный (если $y$ вещественное число). Но **коэффициент перед квадратом** может быть отрицательным.

То есть $-3y^2$ — это не "отрицательный квадрат", а "квадрат с отрицательным коэффициентом".

**Геометрический смысл:**
- Если все коэффициенты положительные ($n_+ = 3, n_- = 0$), то форма всегда положительна — это **эллипсоид** (как сфера, но растянутая).
- Если есть и положительные, и отрицательные коэффициенты ($n_+ = 2, n_- = 1$), то форма может быть как положительной, так и отрицательной — это **гиперболоид** (седловая поверхность).

---

#### 4. Что такое **диагонализуемая матрица**?

Любой квадратичной форме можно сопоставить **симметричную матрицу** $A$. Например, форме $3x^2 + 4xy + 5y^2$ соответствует матрица:
$$A = \begin{pmatrix} 3 & 2 \\ 2 & 5 \end{pmatrix}$$

(Коэффициент при $xy$ делится пополам и идёт в позиции $(1,2)$ и $(2,1)$.)

**Диагонализуемая матрица** — это матрица, которую можно привести к **диагональному виду** с помощью замены координат. Диагональная матрица — это когда все элементы вне главной диагонали равны нулю:
$$D = \begin{pmatrix} \lambda_1 & 0 \\ 0 & \lambda_2 \end{pmatrix}$$

**Почему это важно:** Если матрица диагональна, то квадратичная форма автоматически в каноническом виде! Перекрёстных членов нет.

**Факт:** Любая вещественная симметричная матрица диагонализуема. Это гарантирует **спектральная теорема**.

---

#### 5. Что такое **ортогональное преобразование**?

Это замена координат, которая **не искажает расстояния и углы**. Проще говоря:
- Поворот системы координат
- Отражение (зеркальное отображение)

Матрица ортогонального преобразования $C$ удовлетворяет условию:
$$C^T C = I$$
где $I$ — единичная матрица.

**Аналогия:** Это как если бы ты повернул камеру, снимая объект. Объект не изменился, просто ты смотришь на него под другим углом. Расстояния между точками на объекте остались теми же.

---

#### 6. Что такое **невырожденное** преобразование?

**Невырожденное** = **обратимое** = **не теряющее информацию**.

Матрица $C$ невырождена, если её определитель $\det C \neq 0$. Это значит, что преобразование можно "откатить назад" — перейти от новых координат к старым.

**Аналогия:** Если ты сжал изображение в JPEG с потерями — это **вырожденное** преобразование (информация потеряна). Если ты просто повернул изображение на 90 градусов — это **невырожденное** (можно повернуть обратно, ничего не потерялось).

---

#### 7. Что такое **инвариант**?

**Инвариант** — это свойство, которое **не меняется** при определённых преобразованиях.

**Пример из жизни:**
- Масса объекта — инвариант относительно перемещения в пространстве (ты не становишься легче, если перейдёшь из кухни в спальню).
- Цвет глаз — инвариант относительно смены причёски.

**В нашем случае:** Сигнатура $(n_+, n_-)$ — это инвариант квадратичной формы относительно **невырожденных замен переменных**. То есть, как бы ты ни менял координаты (поворачивал, растягивал, сжимал — лишь бы не терял информацию), количество положительных и отрицательных коэффициентов в каноническом виде **останется тем же**.

</details>

### 3. Алгоритм проверки

1. Составить симметричные матрицы $A_1$ и $A_2$ обеих форм.
2. Найти собственные значения каждой матрицы (они вещественны, так как матрицы симметричны).
3. Посчитать сигнатуры $(n_+, n_-, n_0)$ — количество положительных, отрицательных и нулевых собственных значений.
4. Если сигнатуры совпадают — формы эквивалентны; иначе — нет.

## Решение

### Шаг 1. Матрицы квадратичных форм

$$A_1 = \begin{pmatrix} 2 & 4 & -2 \\ 4 & 9 & -5 \\ -2 & -5 & 3 \end{pmatrix}, \qquad A_2 = \begin{pmatrix} 2 & -2 & -2 \\ -2 & 3 & 4 \\ -2 & 4 & 6 \end{pmatrix}$$

### Шаг 2. Находим собственные значения и сигнатуры

In [ ]:
import numpy as np
import sympy as sp

# Матрицы квадратичных форм
A1 = np.array([
    [ 2,  4, -2],
    [ 4,  9, -5],
    [-2, -5,  3]
], dtype=float)

A2 = np.array([
    [ 2, -2, -2],
    [-2,  3,  4],
    [-2,  4,  6]
], dtype=float)

print("Матрица A₁ формы Q₁:")
print(A1.astype(int))
print("\nМатрица A₂ формы Q₂:")
print(A2.astype(int))

# === ХАРАКТЕРИСТИЧЕСКИЕ ПОЛИНОМЫ (символьные вычисления через SymPy) ===
#
# Характеристический полином матрицы A — это многочлен от λ:
#     p(λ) = det(A - λ·I)
# где I — единичная матрица.
#
# Корни этого полинома (где p(λ) = 0) — это собственные значения матрицы A.
# Мы считаем полином символьно, чтобы увидеть его явный вид (для красоты в отчёте),
# но сами корни находим численно через NumPy — это быстрее и точнее.

lam = sp.Symbol('lambda')                          # создаём символ λ (не число, а переменная)

# Формируем матрицу (A - λ·I):
#   sp.eye(3) — единичная матрица 3×3 (как число 1, но для матриц)
#   lam * sp.eye(3) — это λ·I = diag(λ, λ, λ)
#   sp.Matrix(A1) - lam*sp.eye(3) — вычитаем из A1
#   .det() — считаем определитель этой матрицы → получаем многочлен от λ
char_poly1 = (sp.Matrix(A1) - lam*sp.eye(3)).det()
char_poly2 = (sp.Matrix(A2) - lam*sp.eye(3)).det()

# sp.expand() раскрывает скобки, чтобы полином был в стандартном виде
# (например, превращает (λ-1)(λ-2) в λ² - 3λ + 2)
print("\nQ₁:")
print(f"Характеристический полином: {sp.expand(char_poly1)}")

# === СОБСТВЕННЫЕ ЗНАЧЕНИЯ (численные вычисления через NumPy) ===
#
# np.linalg.eigvalsh(A) находит собственные значения симметричной матрицы A.
# Почему именно eigvalsh, а не eig?
#   - eigvalsh работает ТОЛЬКО с симметричными матрицами (а матрица квадратичной
#     формы всегда симметрична по определению)
#   - он быстрее и надёжнее: не выдаст комплексные числа из-за погрешностей
#   - возвращает только значения (без векторов) — нам векторы не нужны
eig1 = np.linalg.eigvalsh(A1)

# np.sort() сортирует по возрастанию, [::-1] разворачивает → получаем по убыванию
eig1_sorted = np.sort(eig1)[::-1]
print(f"Собственные значения A₁: {eig1_sorted}")

# === ПОДСЧЁТ СИГНАТУРЫ (n₊, n₋, n₀) ===
#
# Почему сравниваем с 1e-10, а не с 0?
#   Компьютер работает с числами с плавающей точкой, и "ноль" может оказаться
#   чем-то вроде 0.0000000001 или -0.0000000001 из-за погрешностей вычислений.
#   Поэтому считаем:
#     - положительным то, что БОЛЬШЕ +10⁻¹⁰
#     - отрицательным то, что МЕНЬШЕ -10⁻¹⁰
#     - нулевым всё, что лежит в интервале [-10⁻¹⁰, +10⁻¹⁰]

n_pos1 = int(np.sum(eig1 > 1e-10))      # количество положительных λ
n_neg1 = int(np.sum(eig1 < -1e-10))     # количество отрицательных λ
n_zero1 = 3 - n_pos1 - n_neg1           # остальные — нулевые (всего 3 значения)
sig1 = (n_pos1, n_neg1, n_zero1)        # сигнатура = тройка (n₊, n₋, n₀)
print(f"Сигнатура Q₁: (n₊={n_pos1}, n₋={n_neg1}, n₀={n_zero1})")

print("\nQ₂:")
print(f"Характеристический полином: {sp.expand(char_poly2)}")
eig2 = np.linalg.eigvalsh(A2)
eig2_sorted = np.sort(eig2)[::-1]
print(f"Собственные значения A₂: {eig2_sorted}")

n_pos2 = int(np.sum(eig2 > 1e-10))
n_neg2 = int(np.sum(eig2 < -1e-10))
n_zero2 = 3 - n_pos2 - n_neg2
sig2 = (n_pos2, n_neg2, n_zero2)
print(f"Сигнатура Q₂: (n₊={n_pos2}, n₋={n_neg2}, n₀={n_zero2})")

# === СРАВНЕНИЕ СИГНАТУР ===
# По закону инерции Сильвестра: формы эквивалентны ⟺ сигнатуры совпадают
print(f"\nСигнатуры совпадают: {sig1} == {sig2}")
if sig1 == sig2:
    print("Формы Q₁ и Q₂ ЭКВИВАЛЕНТНЫ над полем ℝ (по закону инерции Сильвестра).")
else:
    print("Формы Q₁ и Q₂ НЕ эквивалентны.")

Матрица A₁ формы Q₁:
[[ 2  4 -2]
 [ 4  9 -5]
 [-2 -5  3]]

Матрица A₂ формы Q₂:
[[ 2 -2 -2]
 [-2  3  4]
 [-2  4  6]]

Q₁:
Характеристический полином: -lambda**3 + 14.0*lambda**2 - 6.0*lambda
Собственные значения A₁: [ 1.35574385e+01  4.42561476e-01 -1.91443056e-16]
Сигнатура Q₁: (n₊=2, n₋=0, n₀=1)

Q₂:
Характеристический полином: -lambda**3 + 11.0*lambda**2 - 12.0*lambda
Собственные значения A₂: [9.77200187e+00 1.22799813e+00 1.32913689e-15]
Сигнатура Q₂: (n₊=2, n₋=0, n₀=1)

Сигнатуры совпадают: (2, 0, 1) == (2, 0, 1)
Формы Q₁ и Q₂ ЭКВИВАЛЕНТНЫ над полем ℝ (по закону инерции Сильвестра).


<details>
<summary><b>🔍 Разбор кода — что вообще тут происходит (Вырезать перед прикреплением на сдачу)</b></summary>

### Что такое характеристический полином?

**Характеристический полином** матрицы $A$ — это многочлен от переменной $\lambda$, который определяется как:
$$p(\lambda) = \det(A - \lambda I)$$

где $I$ — единичная матрица.

**Зачем он нужен?** Корни этого полинома (значения $\lambda$, при которых $p(\lambda) = 0$) — это и есть **собственные значения** матрицы $A$. То есть, чтобы найти собственные значения, можно:
1. Составить характеристический полином
2. Найти его корни

---

### Построчный разбор кода

#### 1. Создание символической переменной
```python
lam = sp.Symbol('lambda')
```
Создаём символ $\lambda$ для символьных вычислений. Это не число, а именно переменная — SymPy будет обращаться с ней как с буквой в формуле.

---

#### 2. Вычисление характеристического полинома
```python
char_poly1 = (sp.Matrix(A1) - lam*sp.eye(3)).det()
```

**Что здесь происходит:**
- `sp.Matrix(A1)` — превращаем NumPy-массив в SymPy-матрицу (для символьных вычислений)
- `sp.eye(3)` — единичная матрица $3 \times 3$: $\begin{pmatrix} 1 & 0 & 0 \\ 0 & 1 & 0 \\ 0 & 0 & 1 \end{pmatrix}$
- `lam*sp.eye(3)` — матрица $\lambda I = \begin{pmatrix} \lambda & 0 & 0 \\ 0 & \lambda & 0 \\ 0 & 0 & \lambda \end{pmatrix}$
- `sp.Matrix(A1) - lam*sp.eye(3)` — вычисляем $A - \lambda I$
- `.det()` — считаем определитель этой матрицы → получаем многочлен от $\lambda$

**Математически:**
$$A_1 - \lambda I = \begin{pmatrix} 2-\lambda & 4 & -2 \\ 4 & 9-\lambda & -5 \\ -2 & -5 & 3-\lambda \end{pmatrix}$$

Определитель этой матрицы — многочлен третьей степени от $\lambda$:
$$p(\lambda) = -\lambda^3 + 14\lambda^2 - 6\lambda$$

Это и есть **характеристический полином**.

---

#### 3. Раскрытие скобок
```python
print(f"Характеристический полином: {sp.expand(char_poly1)}")
```

`sp.expand` раскрывает скобки, чтобы полином был в стандартном виде (сумма степеней $\lambda$).

**Результат:**
```
Характеристический полином: -λ³ + 14λ² - 6λ
```

---

#### 4. Нахождение собственных значений
```python
eig1 = np.linalg.eigvalsh(A1)
```

Здесь мы **не решаем полином вручную**, а используем численный метод NumPy. Функция `eigvalsh` находит корни характеристического полинома (собственные значения) напрямую из матрицы $A_1$.

**Почему не используем SymPy для решения полинома?**
Потому что:
- SymPy даёт точные символьные ответы (например, $\sqrt{2}$), но это медленно для больших матриц
- NumPy даёт численные приближения (например, $1.414$), но это быстро
- Для проверки сигнатуры нам нужны только **знаки** собственных значений, а не их точные значения

**Почему именно `eigvalsh`, а не `eig`?**
- `eigvalsh` работает **только с симметричными матрицами** (а матрица квадратичной формы всегда симметрична по определению)
- Он быстрее и надёжнее: не выдаст комплексные числа из-за погрешностей вычислений
- Возвращает только значения (без векторов) — нам векторы не нужны

**Результат:**
```
Собственные значения A₁: [13.55743852  0.44256148  0.        ]
```

---

#### 5. Сортировка собственных значений
```python
eig1_sorted = np.sort(eig1)[::-1]
```

- `np.sort(eig1)` — сортирует по возрастанию: `[0, 0.44, 13.56]`
- `[::-1]` — разворачивает список: `[13.56, 0.44, 0]`

Зачем? Чтобы самые большие значения были первыми — так удобнее читать.

---

#### 6. Подсчёт сигнатуры
```python
n_pos1 = int(np.sum(eig1 > 1e-10))
n_neg1 = int(np.sum(eig1 < -1e-10))
n_zero1 = 3 - n_pos1 - n_neg1
```

**Почему `1e-10`, а не просто `> 0`?**
Потому что компьютеры работают с числами с плавающей точкой, и "ноль" может быть на самом деле `0.0000000001` или `-0.0000000001` из-за погрешностей вычислений.

Поэтому мы считаем:
- **Положительными** те значения, которые **больше** $10^{-10}$
- **Отрицательными** те значения, которые **меньше** $-10^{-10}$
- **Нулевыми** всё остальное (то, что лежит в интервале $[-10^{-10}, 10^{-10}]$)

**Результат:**
```
Сигнатура Q₁: (n₊=2, n₋=0, n₀=1)
```

Это значит:
- 2 положительных собственных значения
- 0 отрицательных
- 1 нулевое

---

### Итоговая картина

| Шаг | Что делаем | Зачем |
|---|---|---|
| 1 | Создаём символ $\lambda$ | Для символьных вычислений |
| 2 | Вычисляем $\det(A - \lambda I)$ | Получаем характеристический полином |
| 3 | Раскрываем скобки (`sp.expand`) | Чтобы полином был в читаемом виде |
| 4 | Находим корни полинома (`np.linalg.eigvalsh`) | Чтобы определить сигнатуру |
| 5 | Сортируем | Для удобства чтения |
| 6 | Считаем положительные/отрицательные/нулевые | Получаем сигнатуру $(n_+, n_-, n_0)$ |

**Главная идея:** Характеристический полином — это способ найти собственные значения. Но на практике мы не решаем полином вручную, а используем численные методы (NumPy), которые делают это быстрее и точнее для больших матриц.

---

### Шпаргалка по функциям

```python
# SymPy (символьные вычисления)
sp.eye(3)              # Единичная матрица 3×3
sp.expand(expr)        # Раскрыть скобки

# NumPy (численные вычисления)
np.linalg.eigvalsh(A)  # Собственные значения симметричной матрицы
```

</details>